package com.example.yuanshuai.nao.model;

public class Family {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Family.fid
     *
     * @mbggenerated
     */
    private Integer fid=null;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column Family.fname
     *
     * @mbggenerated
     */
    private String fname;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Family.fid
     *
     * @return the value of Family.fid
     *
     * @mbggenerated
     */
    public Integer getFid() {
        return fid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Family.fid
     *
     * @param fid the value for Family.fid
     *
     * @mbggenerated
     */
    public void setFid(Integer fid) {
        this.fid = fid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column Family.fname
     *
     * @return the value of Family.fname
     *
     * @mbggenerated
     */
    public String getFname() {
        return fname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column Family.fname
     *
     * @param fname the value for Family.fname
     *
     * @mbggenerated
     */
    public void setFname(String fname) {
        this.fname = fname == null ? null : fname.trim();
    }
}